/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.2.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input signed [7:0] c$arg
    , input signed [7:0] c$arg_0

      // Outputs
    , output wire signed [7:0] result
    );


  assign result = c$arg + c$arg_0;


endmodule

